import { MailboxConsumer } from "src/modules/mailbox/assignments/entities/mailbox-consumer.entity";
import { Column, CreateDateColumn, DeleteDateColumn, Entity, Index, OneToMany, PrimaryGeneratedColumn, Unique, UpdateDateColumn } from "typeorm";
import { MailboxSite } from "./enum/mailbox.enum";
import { MailboxStatus } from "./enum/mailbox-status.enum";
import { MailboxItem } from "src/modules/mailbox/items/entites/mailbox-item.entity";

@Entity('mailbox')
@Index('IDX_mailbox_mail_number', ['mail_number'])
@Unique('UQ_mailbox_mail_number_site', ['mail_number', 'mailboxSite'])
export class Mailbox {
    @PrimaryGeneratedColumn()
    id: number; // autogenerated primary key

    @Column()
    mail_number: string; // mailbox number as fake id   

    @OneToMany(
        () => MailboxConsumer,
        (mailboxConsumer) => mailboxConsumer.mailbox,
    )
    mailboxConsumers: MailboxConsumer[];

    @OneToMany(
        () => MailboxItem,
        (mailboxItem) => mailboxItem.mailbox,
    )
    mailboxItems: MailboxItem[];

    @Column(
        {
            type: 'enum',
            enum: MailboxSite
        }
    )
    mailboxSite: MailboxSite;

    @Column({
        type: 'enum',
        enum: MailboxStatus,
        default: MailboxStatus.ACTIVE
    })
    status: MailboxStatus;// status of the mailbox, can be ACTIVE or INACTIVE a analizar

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @DeleteDateColumn()
    deletedAt: Date; 
}
