import { Consumer } from "src/consumer/consumer.entity";
import { MailboxItem } from "src/mailbox_item/mailbox-item.entity";
import { Payments } from "src/payments/payments.entity";
import { Column, CreateDateColumn, DeleteDateColumn, Entity, JoinColumn, OneToMany, ManyToOne, PrimaryGeneratedColumn, UpdateDateColumn, Unique } from "typeorm";
import { MailboxSite } from "./enum/mailbox.enum";

export enum MailboxStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}

@Entity('mailbox')
export class Mailbox {
    @PrimaryGeneratedColumn()
    id: number; // autogenerated primary key

    @Column()
    mail_number: string; // mailbox number as fake id

    @ManyToOne(() => Consumer, consumer => consumer.mailboxs)
    @JoinColumn({
        name: "consumer_id"
    })
    consumer: Consumer; // it changes the consumer of the mailbox, but it is not a foreign key, it is just a relation

    @OneToMany(() => Payments, payments => payments.mailbox)
    payments: Payments[];

    @OneToMany(() => MailboxItem, mailboxItem => mailboxItem.mailbox)
    mailboxItems: MailboxItem[];

    @Column(
        {
            type: 'enum',
            enum: MailboxSite
        }
    )
    mailboxSite: MailboxSite;

    @Column({
        type: 'enum',
        enum: MailboxStatus,
        default: MailboxStatus.ACTIVE
    })
    status: MailboxStatus; // status of the mailbox, either ACTIVE or INACTIVE

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @DeleteDateColumn()
    deletedAt: Date; 
}