import { Payments } from "src/payments/payments.entity";
import { MailboxConsumer } from "src/mailbox_consumer/mailbox-consumer.entity";
import { Column, CreateDateColumn, DeleteDateColumn, Entity, OneToMany, PrimaryGeneratedColumn, UpdateDateColumn } from "typeorm";
import { MailboxSite } from "./enum/mailbox.enum";

export enum MailboxStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}

@Entity('mailbox')
export class Mailbox {
    @PrimaryGeneratedColumn()
    id: number; // autogenerated primary key

    @Column({ unique: true })
    mail_number: string; // mailbox number as fake id

    @OneToMany(
        () => MailboxConsumer,
        (mailboxConsumer) => mailboxConsumer.mailbox,
    )
    mailboxConsumers: MailboxConsumer[];

    @OneToMany(() => Payments, payments => payments.mailbox)
    payments: Payments[];

    @Column(
        {
            type: 'enum',
            enum: MailboxSite
        }
    )
    mailboxSite: MailboxSite;

    @Column({
        type: 'enum',
        enum: MailboxStatus,
        default: MailboxStatus.ACTIVE
    })
    status: MailboxStatus; // status of the mailbox, either ACTIVE or INACTIVE

    @CreateDateColumn()
    createdAt: Date;

    @UpdateDateColumn()
    updatedAt: Date;

    @DeleteDateColumn()
    deletedAt: Date; 
}
